import Image from 'next/image';
import type { Metadata } from 'next';
import { Container } from '@/components/ui/Container';
import { PredictionsGrid } from '@/components/predictions/PredictionsGrid';
import { FavoriteButton } from '@/components/dashboard/FavoriteButton';
import { fetchApi } from '@/lib/api/server';
import { Team, Prediction } from '@/types/api';

interface PageProps {
  params: Promise<{ slug: string }>;
}

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { slug } = await params;
  const { data } = await fetchApi<Team>(`/teams/${slug}`, { revalidate: 3600 });
  if (!data) return { title: 'Team' };
  return {
    title: `${data.name} Predictions`,
    description: `AI predictions for every ${data.name} fixture, generated by our statistical model.`,
  };
}

export default async function TeamDetailPage({ params }: PageProps) {
  const { slug } = await params;
  const { data: team } = await fetchApi<Team>(`/teams/${slug}`, { revalidate: 3600 });

  if (!team) {
    return <Container className="py-24 text-center text-sm text-muted">Team not found.</Container>;
  }

  const { data: predictions } = await fetchApi<Prediction[]>(
    `/predictions?team=${team._id}&limit=12`,
    { revalidate: 300 },
  );

  return (
    <>
      <div className="border-b border-border bg-surface/50 py-10 sm:py-12">
        <Container className="flex flex-wrap items-center justify-between gap-4">
          <div className="flex items-center gap-4">
            <div className="flex h-16 w-16 flex-shrink-0 items-center justify-center rounded-full bg-surface-elevated">
              {team.logoUrl ? (
                <Image src={team.logoUrl} alt={team.name} width={40} height={40} className="object-contain" />
              ) : (
                <span className="font-display text-xl text-muted">{team.name.slice(0, 2).toUpperCase()}</span>
              )}
            </div>
            <div>
              <h1 className="font-display text-2xl font-bold uppercase tracking-tight sm:text-3xl">
                {team.name}
              </h1>
              <p className="mt-1 text-sm text-muted">
                {team.country}
                {team.venueName ? ` · ${team.venueName}` : ''}
              </p>
            </div>
          </div>
          <FavoriteButton id={team._id} type="team" />
        </Container>
      </div>

      <Container className="py-10 sm:py-12">
        <h2 className="mb-6 font-display text-xl font-bold uppercase tracking-tight">
          Upcoming predictions
        </h2>
        <PredictionsGrid
          predictions={predictions ?? []}
          emptyMessage="No predictions for this team's upcoming fixtures yet."
        />
      </Container>
    </>
  );
}
